#!/bin/bash
rsync -avz --delete ~/www/ linux15:www --exclude blog --exclude .git --exclude .gitignore --exclude sync
tsocks rsync -avz --delete ~/www/ droplet:www --exclude blog --exclude .git --exclude .gitignore --exclude sync
